title: Diary of a Lucky Seagull
email: serenadantingchen@gmail.com
description: >-
  D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. D.o.a.L.S. 
url: ""

theme-color: white

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"